version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: pr-project
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - "5432:5432"